#!/usr/bin/env python3
"""Regenerate ``palinode/prompts/shipped-hashes.json`` from this repo's history.

``palinode prompt sync`` refreshes a store's prompt only when it can prove the
store's copy came from some palinode release rather than from the operator's
editor. The proof is this manifest: every prompt *body* hash palinode has ever
shipped. Maintaining it by hand means remembering to prepend a hash in the same
commit that changes a prompt — and a forgotten entry is invisible until an
operator's `prompt sync` refuses to refresh, releases later.

So the manifest is derived instead. Every historical blob of
``specs/prompts/*.md`` (the source of truth) and ``palinode/prompts/*.md`` (the
copies the wheel carries) is body-hashed, newest first. Run this after changing
a prompt, or whenever you want to check the file is still what history says:

    python scripts/regen-prompt-hashes.py           # rewrite the manifest
    python scripts/regen-prompt-hashes.py --output /tmp/x.json   # somewhere else

**Hashes already in the manifest are never dropped.** History here is whatever
this clone has — a shallow clone, or the squashed public release repo, knows
about fewer revisions than the development repo does, and a regeneration that
pruned to what it could see would strand every store running the revisions it
could not. The output is therefore a union, which also makes the script a
fixed point: running it on its own output changes nothing.

The domain is the prompt **body** — frontmatter stripped, exactly the bytes
:func:`palinode.prompts.prompt_body` hands the model. A store decorates prompt
frontmatter on its own (cross-references, descriptions), and hashing that too
made every store prompt look operator-edited. ``hash_domain`` in the manifest
records the choice so a palinode from the whole-file era refuses this file
rather than silently matching nothing.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from palinode.prompts import prompt_body_hash  # noqa: E402

#: Where prompt files have lived, in order of authority. ``specs/prompts`` is
#: the source of truth; ``palinode/prompts`` is the packaged duplicate, scanned
#: too because a revision could have been committed there first.
PROMPT_DIRS = ("specs/prompts", "palinode/prompts")

#: The manifest this writes, relative to the repo root.
MANIFEST = Path("palinode") / "prompts" / "shipped-hashes.json"

SCHEMA = 2
HASH_DOMAIN = "body"

NOTE = (
    "Every prompt-BODY sha256 palinode has ever shipped, per prompt, newest first. "
    "Frontmatter is stripped before hashing: a memory store writes prompt "
    "frontmatter itself (cross-references, descriptions), and hashing it made an "
    "untouched prompt look operator-edited. `palinode prompt sync` refreshes a "
    "store copy only when its body hash appears here - i.e. it is a pristine copy "
    "of some release, not an operator edit. Generated by "
    "scripts/regen-prompt-hashes.py from git history; run it after changing a "
    "prompt rather than editing this file by hand. Existing entries are never "
    "dropped. tests/test_packaged_prompts_match_source.py enforces that the "
    "current shipped bodies are listed."
)


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(  # noqa: S603 — fixed argv, no shell
        ["git", *args], cwd=repo, capture_output=True, text=True, check=True
    ).stdout


def _blob_at(repo: Path, commit: str, path: str) -> str | None:
    """The text of *path* at *commit*, or None when it is not there.

    ``git log -- <path>`` lists the commit that deleted the file too, and a
    merge commit can list a path it does not contain; both are "no revision
    here", not an error.
    """
    result = subprocess.run(  # noqa: S603 — fixed argv, no shell
        ["git", "show", f"{commit}:{path}"], cwd=repo, capture_output=True, check=False
    )
    if result.returncode != 0:
        return None
    try:
        return result.stdout.decode("utf-8")
    except UnicodeDecodeError:
        return None


def historical_body_hashes(repo: Path, name: str) -> list[str]:
    """Every body hash prompt *name* has had in *repo*'s history, newest first.

    Ordered by commit timestamp so the list reads like the release history it
    stands for, and so the two directories a prompt lives in interleave by date
    rather than by which was scanned first.
    """
    seen: dict[str, int] = {}
    for directory in PROMPT_DIRS:
        path = f"{directory}/{name}"
        log = _git(repo, "log", "--all", "--format=%H %ct", "--", path)
        for line in log.splitlines():
            commit, _, timestamp = line.partition(" ")
            text = _blob_at(repo, commit, path)
            if text is None:
                continue
            digest = prompt_body_hash(text)
            seen[digest] = max(seen.get(digest, 0), int(timestamp))
    return [digest for digest, _ in sorted(seen.items(), key=lambda kv: (-kv[1], kv[0]))]


def _existing(path: Path) -> dict[str, list[str]]:
    """The manifest already at *path*, or ``{}`` — any format, hashes only.

    Read permissively on purpose: a manifest from the whole-file era has
    nothing to contribute (its hashes are in another domain and its
    ``hash_domain`` marker is absent), so it is ignored rather than merged.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    if data.get("hash_domain") != HASH_DOMAIN:
        return {}
    prompts = data.get("prompts")
    if not isinstance(prompts, dict):
        return {}
    return {
        str(name): [str(h) for h in hashes]
        for name, hashes in prompts.items()
        if isinstance(hashes, list)
    }


def build_catalogue(repo: Path, existing_path: Path) -> dict[str, object]:
    """The manifest for *repo*: current hash first, then history, then leftovers."""
    existing = _existing(existing_path)
    source_dir = repo / PROMPT_DIRS[0]
    prompts: dict[str, list[str]] = {}
    for source in sorted(source_dir.glob("*.md")):
        current = prompt_body_hash(source.read_text(encoding="utf-8"))
        ordered = [current]
        for digest in historical_body_hashes(repo, source.name) + existing.get(source.name, []):
            if digest not in ordered:
                ordered.append(digest)
        prompts[source.name] = ordered
    return {
        "schema": SCHEMA,
        "hash_domain": HASH_DOMAIN,
        "_note": NOTE,
        "prompts": prompts,
    }


def render(catalogue: dict[str, object]) -> str:
    return json.dumps(catalogue, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--repo", type=Path, default=REPO_ROOT,
        help="Repository to read prompt history from (default: this checkout)",
    )
    parser.add_argument(
        "--catalogue", type=Path, default=None,
        help="Existing manifest to preserve entries from (default: the one in --repo)",
    )
    parser.add_argument(
        "--output", type=Path, default=None,
        help="Where to write (default: the manifest in --repo, rewritten in place)",
    )
    args = parser.parse_args(argv)

    repo = args.repo.resolve()
    catalogue_path = args.catalogue if args.catalogue is not None else repo / MANIFEST
    output_path = args.output if args.output is not None else repo / MANIFEST

    catalogue = build_catalogue(repo, catalogue_path)
    output_path.write_text(render(catalogue), encoding="utf-8")

    prompts: dict[str, list[str]] = catalogue["prompts"]  # type: ignore[assignment]
    total = sum(len(v) for v in prompts.values())
    print(f"{output_path}: {len(prompts)} prompts, {total} body hashes")
    for name, hashes in prompts.items():
        print(f"  {name}: {len(hashes)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
